# Generated by Django 4.0.4 on 2022-05-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.CharField(choices=[('ACCEPTED', 'ПРИНЯТ'), ('IN_PROCESSING', 'В ОБРАБОТКЕ'), ('SENT', 'ОТПРАВЛЕН'), ('RECEIVED', 'ПОЛУЧЕН')], default='ПРИНЯТ', max_length=55, verbose_name='Статус заказа'),
        ),
    ]
